name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  success_etapa1:
    name: etapa [1] success tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build files
        run: make
      - name: Run tests
        run: |
          ./etapa1 < tests/success_etapa1.txt
          if [ $? -eq 1 ] || [ $? -eq 2 ]; then
            echo "Failed"
            exit 1
          fi
      - name: Clean up
        run: make clean
