name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  success_etapa1:
    name: (etapa1) success tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build files
        run: make etapa1_test
      - name: Run tests
        shell: bash
        run: |
          TOTAL_TESTS=0
          ERR_COUNT=0
          SUCCESS_COUNT=0
          LIGHT_RED='\033[0;31m'
          RED='\033[0;38;5;124m'
          GREEN='\033[0;38;5;118m'
          NC='\033[0m'
          error_logs=()
          success_logs=()
          while IFS= read -r line
          do
            TOTAL_TESTS=$(($TOTAL_TESTS + 1))
            output=$(echo "$line" | ./etapa1)
            echo "$output"
            if echo "$output" | grep -q 'TK_ERRO'; then
              ERR_COUNT=$(($ERR_COUNT + 1))
              error_logs+=("[failed] $output")
            else
              SUCCESS_COUNT=$(($SUCCESS_COUNT + 1))
            fi
          done < tests/success_etapa1.txt
          printf "\n"
          echo -e "${NC}$TOTAL_TESTS total: ${GREEN}$SUCCESS_COUNT passed${NC}/${RED}$ERR_COUNT failed${NC}"
          printf "\n"
          if [ $ERR_COUNT -gt 0 ]; then
            for err_log in "${error_logs[@]}"; do
              echo -e "${LIGHT_RED}$err_log${NC}"
            done
            exit 1
          fi
      - name: Clean up
        run: make clean
