name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  success_etapa1:
    name: (etapa1) success tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build files
        run: make etapa1_test
      - name: Run tests
        shell: bash
        run: |
          ERR_COUNT=0
          RED='\033[0;31m'
          NC='\033[0m' # No Color
          error_logs=()
          while IFS= read -r line
          do
            output=$(echo "$line" | ./etapa1)
            if echo "$output" | grep -q 'TK_ERRO'; then
              ERR_COUNT=$(($ERR_COUNT + 1))
              error_logs+=("Failed on $line | Output: $output")
            fi
          done < tests/success_etapa1.txt
          if [ $ERR_COUNT -gt 0 ]; then
            printf "\n"
            for err_log in "${error_logs[@]}"; do
              echo -e "${RED}$err_log${NC}"
            done
            echo -e "${RED}$ERR_COUNT suites failed.${NC}"
            exit 1
          fi
      - name: Clean up
        run: make clean
