name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  success_etapa1:
    name: (etapa1) success tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build files
        run: make
      - name: Run tests
        run: |
          while IFS= read -r line
          do
            echo "$line" | ./etapa1
            if [ $? -eq 1 ] || [ $? -eq 2 ]; then
              echo "Failed on input: $line"
              EXIT_CODE=1
            fi
          done < tests/success_etapa1.txt
          exit ${EXIT_CODE}
      - name: Clean up
        run: make clean
