name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build files
        run: make
      - name: Run tests
        shell: bash
        run: |
          TOTAL_TESTS=0
          ERR_COUNT=0
          SUCCESS_COUNT=0
          RED='\033[0;31m'
          GREEN='\033[0;32m'
          NC='\033[0;38;5;250m'

          for filename in tests/*; do
            TOTAL_TESTS=$(($TOTAL_TESTS + 1))
            if grep -q '//FAIL' "$filename"; then
              expected="FAIL"
              exit_code="1"
            else
              expected="PASS"
              exit_code="0"
            fi

            ./etapa2 < "$filename"

            if [ "$?" -eq "$exit_code" ]; then
              echo "${GREEN}PASS ${NC}$filename"
              SUCCESS_COUNT=$(($SUCCESS_COUNT + 1))
            else
              echo "${RED}FAIL ${NC}$filename"
              ERR_COUNT=$(($ERR_COUNT + 1))
              exit 1
            fi
          done

          printf "\n"
          echo -e "${NC}Tests: $TOTAL_TESTS total → ${GREEN}$SUCCESS_COUNT passed${NC}, ${RED}$ERR_COUNT failed${NC}"
      - name: Clean up
        run: make clean
